name: Merge check for pull requests

on:
  pull_request:
    types: ["opened", "reopened", "edited", "synchronize", "ready_for_review"]

jobs:
  merge-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
      
      - name: Review Code Quality
        run: npm run lint

      - name: The job has failed
        if: ${{ failure() }}
        run: 
          echo "::error::Pull Request cannot be merged due to failed checks." && exit 1